# metadata/region.py

# Provinces and metropolitan cities (17)
PROVINCES_17 = {
    1: "Seoul",
    2: "Incheon",
    3: "Gyeonggi",
    4: "Daejeon",
    5: "Sejong",
    6: "Chungbuk",
    7: "Chungnam",
    8: "Gwangju",
    9: "Jeonbuk",
    10: "Jeonnam",
    11: "Daegu",
    12: "Gyeongbuk",
    13: "Busan",
    14: "Ulsan",
    15: "Gyeongnam",
    16: "Gangwon",
    17: "Jeju",
}

# Municipalities (229)
MUNICIPALITIES_229 = {
    # Seoul (1–25)
    1: ("Seoul", "Jongno-gu"),
    2: ("Seoul", "Jung-gu"),
    3: ("Seoul", "Yongsan-gu"),
    4: ("Seoul", "Seongdong-gu"),
    5: ("Seoul", "Gwangjin-gu"),
    6: ("Seoul", "Dongdaemun-gu"),
    7: ("Seoul", "Jungnang-gu"),
    8: ("Seoul", "Seongbuk-gu"),
    9: ("Seoul", "Gangbuk-gu"),
    10: ("Seoul", "Dobong-gu"),
    11: ("Seoul", "Nowon-gu"),
    12: ("Seoul", "Eunpyeong-gu"),
    13: ("Seoul", "Seodaemun-gu"),
    14: ("Seoul", "Mapo-gu"),
    15: ("Seoul", "Yangcheon-gu"),
    16: ("Seoul", "Gangseo-gu"),
    17: ("Seoul", "Guro-gu"),
    18: ("Seoul", "Geumcheon-gu"),
    19: ("Seoul", "Yeongdeungpo-gu"),
    20: ("Seoul", "Dongjak-gu"),
    21: ("Seoul", "Gwanak-gu"),
    22: ("Seoul", "Seocho-gu"),
    23: ("Seoul", "Gangnam-gu"),
    24: ("Seoul", "Songpa-gu"),
    25: ("Seoul", "Gangdong-gu"),

    # Incheon (26–35)
    26: ("Incheon", "Jung-gu"),
    27: ("Incheon", "Dong-gu"),
    28: ("Incheon", "Michuhol-gu"),
    29: ("Incheon", "Yeonsu-gu"),
    30: ("Incheon", "Namdong-gu"),
    31: ("Incheon", "Bupyeong-gu"),
    32: ("Incheon", "Gyeyang-gu"),
    33: ("Incheon", "Seo-gu"),
    34: ("Incheon", "Ganghwa-gun"),
    35: ("Incheon", "Ongjin-gun"),

    # Gyeonggi (36–66)
    36: ("Gyeonggi", "Suwon-si"),
    37: ("Gyeonggi", "Seongnam-si"),
    38: ("Gyeonggi", "Uijeongbu-si"),
    39: ("Gyeonggi", "Anyang-si"),
    40: ("Gyeonggi", "Bucheon-si"),
    41: ("Gyeonggi", "Gwangmyeong-si"),
    42: ("Gyeonggi", "Pyeongtaek-si"),
    43: ("Gyeonggi", "Dongducheon-si"),
    44: ("Gyeonggi", "Ansan-si"),
    45: ("Gyeonggi", "Goyang-si"),
    46: ("Gyeonggi", "Gwacheon-si"),
    47: ("Gyeonggi", "Guri-si"),
    48: ("Gyeonggi", "Namyangju-si"),
    49: ("Gyeonggi", "Osan-si"),
    50: ("Gyeonggi", "Siheung-si"),
    51: ("Gyeonggi", "Gunpo-si"),
    52: ("Gyeonggi", "Uiwang-si"),
    53: ("Gyeonggi", "Hanam-si"),
    54: ("Gyeonggi", "Yongin-si"),
    55: ("Gyeonggi", "Paju-si"),
    56: ("Gyeonggi", "Icheon-si"),
    57: ("Gyeonggi", "Anseong-si"),
    58: ("Gyeonggi", "Gimpo-si"),
    59: ("Gyeonggi", "Hwaseong-si"),
    60: ("Gyeonggi", "Gwangju-si"),
    61: ("Gyeonggi", "Yangju-si"),
    62: ("Gyeonggi", "Pocheon-si"),
    63: ("Gyeonggi", "Yeoju-si"),
    64: ("Gyeonggi", "Yeoncheon-gun"),
    65: ("Gyeonggi", "Gapyeong-gun"),
    66: ("Gyeonggi", "Yangpyeong-gun"),

    # Daejeon (67–71)
    67: ("Daejeon", "Dong-gu"),
    68: ("Daejeon", "Jung-gu"),
    69: ("Daejeon", "Seo-gu"),
    70: ("Daejeon", "Yuseong-gu"),
    71: ("Daejeon", "Daedeok-gu"),

    # Sejong (72)
    72: ("Sejong", "Sejong-si"),

    # Chungbuk (73–83)
    73: ("Chungbuk", "Cheongju-si"),
    74: ("Chungbuk", "Chungju-si"),
    75: ("Chungbuk", "Jecheon-si"),
    76: ("Chungbuk", "Boeun-gun"),
    77: ("Chungbuk", "Okcheon-gun"),
    78: ("Chungbuk", "Yeongdong-gun"),
    79: ("Chungbuk", "Jeungpyeong-gun"),
    80: ("Chungbuk", "Jincheon-gun"),
    81: ("Chungbuk", "Goesan-gun"),
    82: ("Chungbuk", "Eumseong-gun"),
    83: ("Chungbuk", "Danyang-gun"),

    # Chungnam (84–98)
    84: ("Chungnam", "Cheonan-si"),
    85: ("Chungnam", "Gongju-si"),
    86: ("Chungnam", "Boryeong-si"),
    87: ("Chungnam", "Asan-si"),
    88: ("Chungnam", "Seosan-si"),
    89: ("Chungnam", "Nonsan-si"),
    90: ("Chungnam", "Gyeryong-si"),
    91: ("Chungnam", "Dangjin-si"),
    92: ("Chungnam", "Geumsan-gun"),
    93: ("Chungnam", "Buyeo-gun"),
    94: ("Chungnam", "Seocheon-gun"),
    95: ("Chungnam", "Cheongyang-gun"),
    96: ("Chungnam", "Hongseong-gun"),
    97: ("Chungnam", "Yesan-gun"),
    98: ("Chungnam", "Taean-gun"),

    # Gwangju (99–103)
    99: ("Gwangju", "Dong-gu"),
    100: ("Gwangju", "Seo-gu"),
    101: ("Gwangju", "Nam-gu"),
    102: ("Gwangju", "Buk-gu"),
    103: ("Gwangju", "Gwangsan-gu"),

    # Jeonbuk (104–117)
    104: ("Jeonbuk", "Jeonju-si"),
    105: ("Jeonbuk", "Gunsan-si"),
    106: ("Jeonbuk", "Iksan-si"),
    107: ("Jeonbuk", "Jeongeup-si"),
    108: ("Jeonbuk", "Namwon-si"),
    109: ("Jeonbuk", "Gimje-si"),
    110: ("Jeonbuk", "Wanju-gun"),
    111: ("Jeonbuk", "Jinan-gun"),
    112: ("Jeonbuk", "Muju-gun"),
    113: ("Jeonbuk", "Jangsu-gun"),
    114: ("Jeonbuk", "Imsil-gun"),
    115: ("Jeonbuk", "Sunchang-gun"),
    116: ("Jeonbuk", "Gochang-gun"),
    117: ("Jeonbuk", "Buan-gun"),

    # Jeonnam (118–139)
    118: ("Jeonnam", "Mokpo-si"),
    119: ("Jeonnam", "Yeosu-si"),
    120: ("Jeonnam", "Suncheon-si"),
    121: ("Jeonnam", "Naju-si"),
    122: ("Jeonnam", "Gwangyang-si"),
    123: ("Jeonnam", "Damyang-gun"),
    124: ("Jeonnam", "Gokseong-gun"),
    125: ("Jeonnam", "Gurye-gun"),
    126: ("Jeonnam", "Goheung-gun"),
    127: ("Jeonnam", "Boseong-gun"),
    128: ("Jeonnam", "Hwasun-gun"),
    129: ("Jeonnam", "Jangheung-gun"),
    130: ("Jeonnam", "Gangjin-gun"),
    131: ("Jeonnam", "Haenam-gun"),
    132: ("Jeonnam", "Yeongam-gun"),
    133: ("Jeonnam", "Muan-gun"),
    134: ("Jeonnam", "Hampyeong-gun"),
    135: ("Jeonnam", "Yeonggwang-gun"),
    136: ("Jeonnam", "Jangseong-gun"),
    137: ("Jeonnam", "Wando-gun"),
    138: ("Jeonnam", "Jindo-gun"),
    139: ("Jeonnam", "Sinan-gun"),

    # Daegu (140–147)
    140: ("Daegu", "Jung-gu"),
    141: ("Daegu", "Dong-gu"),
    142: ("Daegu", "Seo-gu"),
    143: ("Daegu", "Nam-gu"),
    144: ("Daegu", "Buk-gu"),
    145: ("Daegu", "Suseong-gu"),
    146: ("Daegu", "Dalseo-gu"),
    147: ("Daegu", "Dalseong-gun"),

    # Gyeongbuk (148–170)
    148: ("Gyeongbuk", "Pohang-si"),
    149: ("Gyeongbuk", "Gyeongju-si"),
    150: ("Gyeongbuk", "Gimcheon-si"),
    151: ("Gyeongbuk", "Andong-si"),
    152: ("Gyeongbuk", "Gumi-si"),
    153: ("Gyeongbuk", "Yeongju-si"),
    154: ("Gyeongbuk", "Yeongcheon-si"),
    155: ("Gyeongbuk", "Sangju-si"),
    156: ("Gyeongbuk", "Mungyeong-si"),
    157: ("Gyeongbuk", "Gyeongsan-si"),
    158: ("Gyeongbuk", "Gunwi-gun"),
    159: ("Gyeongbuk", "Uiseong-gun"),
    160: ("Gyeongbuk", "Cheongsong-gun"),
    161: ("Gyeongbuk", "Yeongyang-gun"),
    162: ("Gyeongbuk", "Yeongdeok-gun"),
    163: ("Gyeongbuk", "Cheongdo-gun"),
    164: ("Gyeongbuk", "Goryeong-gun"),
    165: ("Gyeongbuk", "Seongju-gun"),
    166: ("Gyeongbuk", "Chilgok-gun"),
    167: ("Gyeongbuk", "Yecheon-gun"),
    168: ("Gyeongbuk", "Bonghwa-gun"),
    169: ("Gyeongbuk", "Uljin-gun"),
    170: ("Gyeongbuk", "Ulleung-gun"),

    # Busan (171–186)
    171: ("Busan", "Jung-gu"),
    172: ("Busan", "Seo-gu"),
    173: ("Busan", "Dong-gu"),
    174: ("Busan", "Yeongdo-gu"),
    175: ("Busan", "Busanjin-gu"),
    176: ("Busan", "Dongnae-gu"),
    177: ("Busan", "Nam-gu"),
    178: ("Busan", "Buk-gu"),
    179: ("Busan", "Haeundae-gu"),
    180: ("Busan", "Saha-gu"),
    181: ("Busan", "Geumjeong-gu"),
    182: ("Busan", "Gangseo-gu"),
    183: ("Busan", "Yeonje-gu"),
    184: ("Busan", "Suyeong-gu"),
    185: ("Busan", "Sasang-gu"),
    186: ("Busan", "Gijang-gun"),

    # Ulsan (187–191)
    187: ("Ulsan", "Jung-gu"),
    188: ("Ulsan", "Nam-gu"),
    189: ("Ulsan", "Dong-gu"),
    190: ("Ulsan", "Buk-gu"),
    191: ("Ulsan", "Ulju-gun"),

    # Gyeongnam (192–209)
    192: ("Gyeongnam", "Changwon-si"),
    193: ("Gyeongnam", "Jinju-si"),
    194: ("Gyeongnam", "Tongyeong-si"),
    195: ("Gyeongnam", "Sacheon-si"),
    196: ("Gyeongnam", "Gimhae-si"),
    197: ("Gyeongnam", "Miryang-si"),
    198: ("Gyeongnam", "Geoje-si"),
    199: ("Gyeongnam", "Yangsan-si"),
    200: ("Gyeongnam", "Uiryeong-gun"),
    201: ("Gyeongnam", "Haman-gun"),
    202: ("Gyeongnam", "Changnyeong-gun"),
    203: ("Gyeongnam", "Goseong-gun"),
    204: ("Gyeongnam", "Namhae-gun"),
    205: ("Gyeongnam", "Hadong-gun"),
    206: ("Gyeongnam", "Sancheong-gun"),
    207: ("Gyeongnam", "Hamyang-gun"),
    208: ("Gyeongnam", "Geochang-gun"),
    209: ("Gyeongnam", "Hapcheon-gun"),

    # Gangwon (210–227)
    210: ("Gangwon", "Chuncheon-si"),
    211: ("Gangwon", "Wonju-si"),
    212: ("Gangwon", "Gangneung-si"),
    213: ("Gangwon", "Donghae-si"),
    214: ("Gangwon", "Taebaek-si"),
    215: ("Gangwon", "Sokcho-si"),
    216: ("Gangwon", "Samcheok-si"),
    217: ("Gangwon", "Hongcheon-gun"),
    218: ("Gangwon", "Hoengseong-gun"),
    219: ("Gangwon", "Yeongwol-gun"),
    220: ("Gangwon", "Pyeongchang-gun"),
    221: ("Gangwon", "Jeongseon-gun"),
    222: ("Gangwon", "Cheorwon-gun"),
    223: ("Gangwon", "Hwacheon-gun"),
    224: ("Gangwon", "Yanggu-gun"),
    225: ("Gangwon", "Inje-gun"),
    226: ("Gangwon", "Goseong-gun"),
    227: ("Gangwon", "Yangyang-gun"),

    # Jeju (228–229)
    228: ("Jeju", "Jeju-si"),
    229: ("Jeju", "Seogwipo-si"),
}

# Region hierarchy
REGION_HIERARCHY = {
    "Seoul": list(range(1, 26)),
    "Incheon": list(range(26, 36)),
    "Gyeonggi": list(range(36, 67)),
    "Daejeon": list(range(67, 72)),
    "Sejong": [72],
    "Chungbuk": list(range(73, 84)),
    "Chungnam": list(range(84, 99)),
    "Gwangju": list(range(99, 104)),
    "Jeonbuk": list(range(104, 118)),
    "Jeonnam": list(range(118, 140)),
    "Daegu": list(range(140, 148)),
    "Gyeongbuk": list(range(148, 171)),
    "Busan": list(range(171, 187)),
    "Ulsan": list(range(187, 192)),
    "Gyeongnam": list(range(192, 210)),
    "Gangwon": list(range(210, 228)),
    "Jeju": list(range(228, 230)),
}